#!/bin/bash

###
### Setup myNode (x86_64 devices)
### Run with "sudo"
###

echo "*****************************"
echo "*** myNode x86_64 basic install ***"
echo "*****************************"

sleep 1
sudo -v

set -x
set -e

# Usage: $0 <ip address | online>
if [ "$#" != "1" ]; then
    echo "Install ONLINE..."
    SERVER_IP=online
else
    echo "Install IP ADDRESS... " $1
    SERVER_IP=$1
fi

# Determine Device
sudo apt install lsb-release

IS_X86=0
IS_32_BIT=0
IS_64_BIT=0
IS_UNKNOWN=1
DEVICE_TYPE="unknown"
LINUX=$(lsb_release -i | awk -F ":" '{printf tolower($2)}' | sed -e 's/^[[:space:]]*//')
if [ $LINUX == "pop" ]; then
    LINUX="ubuntu"
fi   
DEBIAN_VERSION=$(lsb_release -c -s) || DEBIAN_VERSION="unknown"
uname -a | grep x86_64 && IS_X86=1 && IS_64_BIT=1 && IS_UNKNOWN=0 || true
if [ $IS_UNKNOWN = 1 ]; then
    echo "UNKNOWN DEVICE TYPE"
    exit 1
fi


# Set kernel settings
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1


# Set DNS for install (new)
sudo bash -c "echo '' >> /etc/dhcp/dhclient.conf"
sudo bash -c "echo 'append domain-name-servers 1.1.1.1, 8.8.8.8;' >> /etc/dhcp/dhclient.conf"
sudo dhclient -r


# Download rootfs
sudo rm -rf /tmp/rootfs.tar.gz
sudo rm -rf /tmp/upgrade/
sudo mkdir -p /tmp/upgrade

TARBALL=""
if [ $IS_X86 = 1 ]; then
    TARBALL="mynode_rootfs_debian.tar.gz"
fi
if [ "$SERVER_IP" == "online" ]; then
    TARBALL="${TARBALL/"mynode_rootfs_"/"mynode_release_latest_"}"
    sudo wget https://mynodebtc.com/device/upgrade_images/${TARBALL} -O /tmp/rootfs.tar.gz
else
    sudo wget http://${SERVER_IP}:8000/${TARBALL} -O /tmp/rootfs.tar.gz
fi

# Extract rootfs (so we can reference temporary files)
sudo tar -xvf /tmp/rootfs.tar.gz -C /tmp/upgrade/
TMP_INSTALL_PATH="/tmp/upgrade/out/rootfs_*"

# Setup some dependencies
sudo mkdir -p /usr/share/mynode/
sudo cp -f /tmp/upgrade/out/rootfs_*/usr/share/mynode/mynode_device_info.sh /usr/share/mynode/mynode_device_info.sh
sudo cp -f /tmp/upgrade/out/rootfs_*/usr/share/mynode/mynode_config.sh /usr/share/mynode/mynode_config.sh
sudo cp -f /tmp/upgrade/out/rootfs_*/usr/share/mynode/mynode_functions.sh /usr/share/mynode/mynode_functions.sh
sudo cp -f /tmp/upgrade/out/rootfs_*/usr/bin/mynode-get-device-serial /usr/bin/mynode-get-device-serial

# Source file containing app versions
source /tmp/upgrade/out/rootfs_*/usr/share/mynode/mynode_app_versions.sh

# Create any necessary users
sudo useradd -p $(openssl passwd -1 bolt) -m -s /bin/bash admin || true
sudo useradd -m -s /bin/bash bitcoin || true
sudo useradd -m -s /bin/bash joinmarket || true
sudo passwd -l root
sudo adduser admin sudo

# Setup bitcoin user folders
sudo mkdir -p /home/bitcoin/.mynode/
sudo chown bitcoin:bitcoin /home/bitcoin
sudo chown -R bitcoin:bitcoin /home/bitcoin/.mynode/


# Update sources
sudo apt-get -y update --allow-releaseinfo-change

# install SSH
sudo apt-get -y install ssh

# Add sources
sudo apt-get -y install apt-transport-https curl gnupg ca-certificates

# tor project
if [ $IS_64_BIT = 1 ]; then
    sudo grep -qxF "deb https://deb.torproject.org/torproject.org ${DEBIAN_VERSION} main" /etc/apt/sources.list  || sudo bash -c "echo 'deb https://deb.torproject.org/torproject.org ${DEBIAN_VERSION} main' >> /etc/apt/sources.list"
    sudo grep -qxF "deb-src https://deb.torproject.org/torproject.org ${DEBIAN_VERSION} main" /etc/apt/sources.list  || sudo bash -c "echo 'deb-src https://deb.torproject.org/torproject.org ${DEBIAN_VERSION} main' >> /etc/apt/sources.list"
    sudo grep -qxF "deb http://deb.debian.org/debian ${DEBIAN_VERSION}-backports main" /etc/apt/sources.list  || sudo bash -c "echo 'deb http://deb.debian.org/debian ${DEBIAN_VERSION}-backports main' >> /etc/apt/sources.list"
fi
#if [ "$DEBIAN_VERSION" = "buster" ]; then
#    sudo grep -qxF "deb http://deb.debian.org/debian ${DEBIAN_VERSION}-backports main" /etc/apt/sources.list  || sudo bash -c "echo 'deb http://deb.debian.org/debian ${DEBIAN_VERSION}-backports main' >> /etc/apt/sources.list"
#fi

# torrc.d dir
sudo mkdir -p /etc/torrc.d

#################################

# Add I2P Repo
# /bin/bash $TMP_INSTALL_PATH/usr/share/mynode/scripts/add_i2p_repo.sh
# Not working when Pop_OS
echo "Importing I2P signing key"
sudo wget -q -O - https://repo.i2pd.xyz/r4sas.gpg | sudo apt-key --keyring /etc/apt/trusted.gpg.d/i2pd.gpg add -
echo "Adding I2P APT repository"
sudo bash -c "echo 'deb https://repo.i2pd.xyz/$LINUX $DEBIAN_VERSION main' > /etc/apt/sources.list.d/i2pd.list"
sudo bash -c "echo 'deb-src https://repo.i2pd.xyz/$LINUX $DEBIAN_VERSION main' >> /etc/apt/sources.list.d/i2pd.list"

##################################

# Import Keys
# wget https://raw.githubusercontent.com/bitcoin/bitcoin/master/contrib/builder-keys/keys.txt -O keys.txt
# while read fingerprint keyholder_name; do gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys ${fingerprint}; done < ./keys.txt

sudo curl https://keybase.io/roasbeef/pgp_keys.asc | sudo gpg --import
sudo curl https://keybase.io/bitconner/pgp_keys.asc | sudo gpg --import
sudo curl https://keybase.io/guggero/pgp_keys.asc | sudo gpg --import # Pool
sudo curl https://raw.githubusercontent.com/JoinMarket-Org/joinmarket-clientserver/master/pubkeys/AdamGibson.asc | sudo gpg --import
sudo gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 01EA5486DE18A882D4C2684590C8019E36C2E964
sudo gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys E777299FC265DD04793070EB944D35F9AC3DB76A # Bitcoin - Michael Ford (fanquake)
sudo curl https://keybase.io/suheb/pgp_keys.asc | sudo gpg --import
sudo curl https://samouraiwallet.com/pgp.txt | sudo gpg --import # two keys from Samourai team
sudo gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys DE23E73BFA8A0AD5587D2FCDE80D2F3F311FD87E #loopd
sudo gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 26984CB69EB8C4A26196F7A4D7D916376026F177 # Lightning Terminal
sudo wget -q https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc -O- | sudo apt-key add - # Tor
#sudo wget -qO- https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --dearmor | tee /usr/share/keyrings/tor-archive-keyring.gpg > /dev/null
sudo gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 648ACFD622F3D138     # Debian Backports
sudo gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9     # Debian Backports
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 74A941BA219EC810   # Tor
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 66F6C87B98EBCFE2   # I2P (R4SAS)

##################################

# Update OS
# Needed to accept new repos
sudo apt update 

# Freeze any packages we don't want to update
if [ $IS_X86 = 1 ]; then
    sudo apt-mark hold grub*
fi

# Upgrade packages
sudo apt-get -y upgrade

# Install other tools (run section multiple times to make sure success)
export DEBIAN_FRONTEND=noninteractive
sudo apt-get -y install apt-transport-https lsb-release
sudo apt-get -y install htop git curl bash-completion jq dphys-swapfile lsof libzmq3-dev
sudo apt-get -y install build-essential python3-dev python3-pip python3-grpcio
sudo apt-get -y install transmission-cli fail2ban ufw tclsh redis-server
sudo apt-get -y install clang hitch zlib1g-dev libffi-dev file toilet ncdu
sudo apt-get -y install toilet-fonts avahi-daemon figlet libsecp256k1-dev
sudo apt-get -y install inotify-tools libssl-dev tor tmux screen fonts-dejavu
sudo apt-get -y install pv sysstat network-manager rsync parted unzip pkg-config
sudo apt-get -y install libfreetype6-dev libpng-dev libatlas-base-dev libgmp-dev libltdl-dev
sudo apt-get -y install libffi-dev libssl-dev python3-bottle automake libtool libltdl7
sudo apt-get -y -qq install apt-transport-https ca-certificates
sudo apt-get -y install openjdk-11-jre libevent-dev ncurses-dev
sudo apt-get -y install zlib1g-dev libudev-dev libusb-1.0-0-dev python3-venv gunicorn
sudo apt-get -y install sqlite3 libsqlite3-dev torsocks python3-requests libsystemd-dev
sudo apt-get -y install libjpeg-dev zlib1g-dev psmisc hexyl libbz2-dev liblzma-dev netcat-openbsd
sudo apt-get -y install hdparm iotop nut obfs4proxy libpq-dev socat btrfs-progs i2pd

##################################

# Install packages dependent on Debian release
if [ "$DEBIAN_VERSION" == "bullseye" ] || [ "$DEBIAN_VERSION" == "jammy" ]; then
    sudo apt-get -y install wireguard
elif [ "$DEBIAN_VERSION" == "buster" ]; then
    $TORIFY sudo apt-get -y -t buster-backports install wireguard
else
    echo .
    echo "========================================="
    echo "== UNKNOWN DEBIAN VERSION: $DEBIAN_VERSION"
    echo "== SOME APPS MAY NOT WORK PROPERLY"
    echo "========================================="
    echo .
fi

# Install Openbox GUI if not desktop available
if [ $IS_X86 = 1 ] && [ -z $DESKTOP_SESSION ]; then
    sudo apt-get -y install xorg chromium openbox lightdm
fi

# Install device specific packages
if [ $IS_X86 = 1 ]; then
    sudo apt-get -y install cloud-init
fi

# Make sure some software is removed
sudo apt-get -y purge ntp # (conflicts with systemd-timedatectl)
if [ $(lsb_release -i | awk -F ":" '{printf tolower($2)}') != "pop" ]; then
    sudo apt-get -y purge chrony # (conflicts with systemd-timedatectl)
fi

# Install other things without recommendation
sudo apt-get -y install --no-install-recommends expect


# Install nginx
sudo mkdir -p /var/log/nginx
$TORIFY sudo apt-get -y install nginx || true
# Install may fail, so we need to edit the default config file and reconfigure
sudo rm -f /etc/nginx/modules-enabled/50-mod-* || true
sudo touch /etc/nginx/sites-available/default
sudo dpkg --configure -a


# Update users
sudo usermod -a -G debian-tor bitcoin

# Make admin a member of bitcoin
sudo adduser admin bitcoin
sudo adduser joinmarket bitcoin
sudo bash -c "grep 'joinmarket' /etc/sudoers || (echo 'joinmarket ALL=(ALL) NOPASSWD:ALL' | EDITOR='tee -a' visudo)"


# Install Python3 (latest)
CURRENT_PYTHON3_VERSION=$(python3 --version)
if [[ "$CURRENT_PYTHON3_VERSION" != *"Python ${PYTHON_VERSION}"* ]]; then
    sudo mkdir -p /opt/download
    cd /opt/download
    sudo rm -rf Python-*

    sudo wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz -O python.tar.xz
    sudo tar xf python.tar.xz

    cd Python-*
    sudo ./configure
    sudo make -j $(nproc)
    sudo make install
    cd ~
else
    echo "Python up to date"
fi


# Install Python3 specific tools
sudo pip3 install --upgrade pip wheel setuptools

sudo pip3 install -r $TMP_INSTALL_PATH/usr/share/mynode/mynode_pip3_requirements.txt --no-cache-dir || \
    sudo pip3 install -r $TMP_INSTALL_PATH/usr/share/mynode/mynode_pip3_requirements.txt --no-cache-dir --use-deprecated=html5lib



# Install node
if [ ! -f /tmp/installed_node ]; then
    sudo curl -sL https://deb.nodesource.com/setup_$NODE_JS_VERSION | sudo bash -
    sudo apt-get install -y nodejs
    sudo touch /tmp/installed_node
fi

# Install docker
sudo mkdir -p /etc/apt/keyrings
if [ LINUX == "debian" ]; then
    sudo curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo bash -c "echo \
      'deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable' | tee /etc/apt/sources.list.d/docker.list > /dev/null"
    sudo apt-get update --allow-releaseinfo-change
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin || true
elif [ LINUX == "ubuntu" ]; then
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo bash -c "echo \
      'deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable' | tee /etc/apt/sources.list.d/docker.list > /dev/null"
    sudo apt-get update --allow-releaseinfo-change
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin || true 
else
    sudo apt update --allow-releaseinfo-change
    sudo apt install -y docker docker-compose
fi
# Use systemd for managing docker
sudo rm -f /etc/init.d/docker
sudo rm -f /etc/systemd/system/multi-user.target.wants/docker.service
sudo systemctl -f enable docker.service

sudo groupadd docker || true
sudo usermod -aG docker admin
sudo usermod -aG docker bitcoin
sudo usermod -aG docker root

##################################

# Install node packages
sudo npm install -g pug-cli browserify uglify-js babel-cli
sudo npm install -g npm@$NODE_NPM_VERSION
sudo npm install -g yarn


#########################################################


# Install Bitcoin
echo .
echo "**********************************"
echo "*** Installing Bitcoin core... ***"
echo "**********************************"
echo .

ARCH="x86_64-linux-gnu"

BTC_UPGRADE_URL=https://bitcoincore.org/bin/bitcoin-core-$BTC_VERSION/bitcoin-$BTC_VERSION-$ARCH.tar.gz
BTC_UPGRADE_SHA256SUM_URL=https://bitcoincore.org/bin/bitcoin-core-$BTC_VERSION/SHA256SUMS
BTC_UPGRADE_SHA256SUM_ASC_URL=https://bitcoincore.org/bin/bitcoin-core-$BTC_VERSION/SHA256SUMS.asc
BTC_CLI_COMPLETION_URL=https://raw.githubusercontent.com/bitcoin/bitcoin/master/contrib/completions/bash/bitcoin-cli.bash
CURRENT=""
if [ -f $BTC_VERSION_FILE ]; then
    CURRENT=$(cat $BTC_VERSION_FILE)
fi
if [ "$CURRENT" != "$BTC_VERSION" ]; then
    # Download and install Bitcoin
    sudo rm -rf /opt/download
    sudo mkdir -p /opt/download
    cd /opt/download

    sudo wget $BTC_UPGRADE_URL
    sudo wget $BTC_UPGRADE_SHA256SUM_URL -O SHA256SUMS
    sudo wget $BTC_UPGRADE_SHA256SUM_ASC_URL -O SHA256SUMS.asc

    sudo sha256sum --ignore-missing --check SHA256SUMS

    #sudo gpg --verify SHA256SUMS.asc SHA256SUMS
    #VAL=$?
    #if [ $VAL == 0 ]; then
    #    echo "Good signature..."
    #else
    #    echo "No good signature..."
    #fi


    CHECKSUM=$(sha256sum --ignore-missing --check SHA256SUMS)
    VALORCHECKSUM=$?
    if [ $VALORCHECKSUM -eq 0 ]; then	
    	echo "OK..."
    	echo $(sha256sum --ignore-missing --check SHA256SUMS | awk -F ":" '{printf tolower($2)}')	
    else
    	echo "KO..."
    	echo $(sha256sum --ignore-missing --check SHA256SUMS | awk -F ":" '{printf tolower($2)}')
    	exit $VALORCHECKSUM
    fi
    
    curl -s "https://api.github.com/repositories/355107265/contents/builder-keys" | grep download_url | grep -oE "https://[a-zA-Z0-9./-]+" | while read url; do curl -s "$url" | gpg --import; done
    gpg --verify SHA256SUMS.asc
    

    # Install Bitcoin
    sudo tar -xvf bitcoin-$BTC_VERSION-$ARCH.tar.gz
    sudo mv bitcoin-$BTC_VERSION bitcoin
    sudo install -m 0755 -o root -g root -t /usr/local/bin bitcoin/bin/*
    
    if [ ! -L /home/bitcoin/.bitcoin ]; then
        sudo rm -f /home/bitcoin/.bitcoin
        sudo -u bitcoin ln -s /mnt/hdd/mynode/bitcoin /home/bitcoin/.bitcoin
    fi
    
    sudo mkdir -p /home/admin/.bitcoin
    
    sudo -u bitcoin echo $BTC_VERSION | sudo -u bitcoin tee BTC_VERSION_FILE

    # Install bash-completion for bitcoin-cli
    sudo wget $BTC_CLI_COMPLETION_URL -O bitcoin-cli.bash
    sudo cp bitcoin-cli.bash /etc/bash_completion.d/bitcoin-cli
    
    sudo rm -rf /opt/download/*
    cd
fi


# Install Electrs (just mark version, now included in overlay)
echo .
echo "Installing Electrs..."
echo .

ELECTRS_VERSION_FILE=$(echo $ELECTRS_VERSION)


# Install recent version of secp256k1
echo .
echo "****************************************"
echo "Installing secp256k1..."
echo "****************************************"
echo .

SECP256K1_UPGRADE_URL=https://github.com/bitcoin-core/secp256k1/archive/$SECP256K1_VERSION.tar.gz
CURRENT=""
if [ -f $SECP256K1_VERSION_FILE ]; then
    CURRENT=$(cat $SECP256K1_VERSION_FILE)
fi
if [ "$CURRENT" != "$SECP256K1_VERSION" ]; then
    sudo rm -rf /tmp/secp256k1
    cd /tmp/
    sudo git clone https://github.com/bitcoin-core/secp256k1.git
    cd secp256k1

    sudo ./autogen.sh
    sudo ./configure --enable-module-recovery --disable-jni --enable-experimental --enable-module-ecdh --enable-benchmark=no
    sudo make -j $(nproc)
    sudo make install
    sudo cp -f include/* /usr/include/
    sudo rm -rf /tmp/secp256k1
    cd

    SECP256K1_VERSION_FILE=$(echo $SECP256K1_VERSION)
fi

# Install ngrok for debugging
echo .
echo "****************************************"
echo "Installing ngrok for debugging..."
echo "****************************************"
echo .

if [ ! -f /usr/bin/ngrok  ]; then
    sudo rm -rf /tmp/ngrok
    sudo mkdir -p /tmp/ngrok
    cd /tmp/ngrok
    NGROK_URL=https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip
    sudo wget $NGROK_URL
    sudo unzip ngrok-*.zip
    sudo cp ngrok /usr/bin/
    sudo rm -rf /tmp/ngrok
    cd
fi

# Make sure "Remote Access" apps are marked installed
sudo touch /home/bitcoin/.mynode/install_tor
sudo touch /home/bitcoin/.mynode/install_premium_plus
sudo touch /home/bitcoin/.mynode/install_vpn

# Mark docker images for install (on SD so install occurs after drive attach)
sudo touch /home/bitcoin/.mynode/install_mempool
sudo touch /home/bitcoin/.mynode/install_btcpayserver
sudo touch /home/bitcoin/.mynode/install_dojo

# SKIPPING LNBITS - OPTIONAL ALL
# SKIPPING CKBUNKER - OPTIONAL APP
# SKIPPING SPHINX - OPTIONAL APP
# SKIPPING BOS - OPTIONAL APP
# SKIPPING PYBLOCK - OPTIONAL APP
# SKIPPING WARDEN - OPTIONAL APP


# Make sure we are using legacy iptables
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy || true
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy || true


#########################################################


# Install files (downloaded and extracted earlier)
sudo rsync -r -K /tmp/upgrade/out/rootfs_*/* /
sudo sync
sleep 1


# Mark dynamic applications as defalt application
# ... (none yet)

# Upgrade Dyanmic Applications (must be done after file installation)
# mynode-manage-apps upgrade # not yet working during setup process


# Random Cleanup
sudo rm -rf /opt/download
sudo mkdir -p /opt/download

# Clean apt-cache
sudo apt-get -y autoclean
sudo apt-get -y autoremove

# Setup myNode Startup Script
sudo systemctl daemon-reload
sudo systemctl enable check_in
sudo systemctl enable premium_plus_connect
sudo systemctl enable background
sudo systemctl enable docker
sudo systemctl enable quicksync
sudo systemctl enable torrent_check
sudo systemctl enable firewall
sudo systemctl enable bandwidth
sudo systemctl enable www
sudo systemctl enable drive_check
sudo systemctl enable bitcoin
sudo systemctl enable seed_bitcoin_peers
sudo systemctl enable lnd
sudo systemctl enable loop
sudo systemctl enable pool
sudo systemctl enable lit
sudo systemctl enable lnd_backup
sudo systemctl enable lnd_admin_files
sudo systemctl enable lndconnect
sudo systemctl enable redis-server
#systemctl enable mongodb
#systemctl enable electrs # DISABLED BY DEFAULT
#systemctl enable lndhub # DISABLED BY DEFAULT
#systemctl enable btcrpcexplorer # DISABLED BY DEFAULT
sudo systemctl enable rtl
sudo systemctl enable tor
sudo systemctl enable i2pd
sudo systemctl enable invalid_block_check
sudo systemctl enable usb_driver_check
sudo systemctl enable docker_images
sudo systemctl enable glances
#systemctl enable netdata # DISABLED BY DEFAULT
sudo systemctl enable webssh2
sudo systemctl enable rotate_logs
sudo systemctl enable corsproxy_btcrpc
sudo systemctl enable usb_extras
sudo systemctl enable ob-watcher

# and now... myNode start
sudo systemctl enable mynode

# Disable services
sudo systemctl disable hitch || true
sudo systemctl disable mongodb || true
sudo systemctl disable dhcpcd || true


# Delete junk
sudo rm -rf /home/admin/download
sudo rm -rf /home/admin/.bash_history
sudo rm -rf /home/bitcoin/.bash_history
sudo rm -rf /root/.bash_history
sudo rm -rf /root/.ssh/known_hosts
sudo rm -rf /etc/resolv.conf
sudo rm -rf /tmp/*
sudo rm -rf ~/setup_device.sh

# Remove existing MOTD login info
sudo rm -rf /etc/motd # Remove simple motd for update-motd.d
sudo rm -rf /etc/update-motd.d/*

# Remove default debian stuff
sudo deluser mynode || true
sudo rm -rf /home/mynode || true

# Add fsck force to startup for x86
if [ $IS_X86 = 1 ]; then
    sudo sed -i "s/GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT=\"quiet fsck.mode=force fsck.repair=yes\"/g" /etc/default/grub
    sudo update-grub
fi

# Add generic boot option if UEFI
if [ -f /boot/efi/EFI/debian/grubx64.efi ]; then
    sudo mkdir -p /boot/efi/EFI/BOOT
    sudo cp -f /boot/efi/EFI/debian/grubx64.efi /boot/efi/EFI/BOOT/bootx64.efi
fi

# NOT Expand Root FS
sudo mkdir -p /var/lib/mynode
sudo touch /var/lib/mynode/.expanded_rootfs
sudo sync

# Update host info
sudo hostnamectl set-hostname myNode # sudo echo "myNode" > /etc/hostname

set +x
echo ""
echo ""
echo "##################################"
echo "          SETUP COMPLETE          "
echo "   Reboot your device to begin!   "
echo "##################################"
echo ""
echo ""
echo "You can inspect status myNode with this command:"
echo "sudo journalctl -f -u mynode"
echo ""
echo .
